it_companies = {'Facebook', 'Google', 'Microsoft', 'Apple', 'IBM', 'Oracle', 'Amazon'}
A = {19, 22, 24, 20, 25, 26}
B = {19, 22, 20, 25, 26, 24, 28, 27}
age = [22, 19, 24, 25, 26, 24, 25, 24]
print('number of companies:')
print(len(it_companies))
it_companies.add("Twitter")
print(it_companies)
it_companies.update(['wipro','servicenow','T-mobile'])
print(it_companies)
it_companies.discard('Google')
print(it_companies)
print("the difference between remove and discard : the remove() method will raise an error if the specified item does not exist, and the discard() method will not")
print("Union of A and B is ")
print(A.union(B))
print("Intersection of A and B is ")
print(A.intersection(B))
print("A is subset of B :")
print(A.issubset(B))
print("A and B are disjoint set:")
print(A.isdisjoint(B))
print("A with B and B with A:")
print(A.union(B).intersection(B.union(A)))
print("Symmetric difference of A with B:")
print(A.symmetric_difference(B))
A.clear()
B.clear()
print("after clearing set A:",A)
print("after clearing set B:",B)
print("age list: ",age)
age_set = set(age)
print("set of ageslist: ", age_set)
print("Lenght of age list: ")
print(len(age))
print("lenght of age set: " )
print(len(age_set))